#!/usr/bin/env python
# Copyright 2026 The HuggingFace Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate the parts of the docs site that are derived from the repo rather than hand-written.

Three outputs, all git-ignored and rebuilt by ``make docs`` and by the Pages workflow, so the repo stays
the single source of truth and the site can never document something that no longer exists:

* ``docs/rules/`` — the searchable rule index plus one page per rule, from ``mlinter/rules.toml``.
  Retired rules keep a page too: a `TRFNNN` in an old CI log or an old `# trf-ignore` comment has to
  stay findable, and a 404 does not tell the reader the rule is gone rather than mistyped.
* ``docs/changelog.md`` — the root ``CHANGELOG.md`` with site front matter prepended.
* ``docs/_data/mlinter.yml`` — the released version, for pages to display.

The rule specs are read through the public ``mlinter`` API rather than by parsing the TOML here, so a
rule that fails the package's own spec validation fails this build too.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path
from typing import cast


# Same fallback as mlinter/mlinter.py: tomllib is stdlib only from 3.11, and this project supports 3.10,
# where the `tomli` dependency stands in for it.
try:
    import tomllib  # Python >= 3.11
except ModuleNotFoundError:
    import tomli as tomllib  # Python 3.10 fallback


REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import mlinter  # noqa: E402  (needs the repo root on sys.path when run from a checkout)


REPO_URL = "https://github.com/huggingface/transformers-mlinter"
DOCS_DIR = REPO_ROOT / "docs"
DEFAULT_OUTPUT_DIR = DOCS_DIR / "rules"
CHANGELOG_SRC = REPO_ROOT / "CHANGELOG.md"

GENERATED_BANNER = "<!-- Generated by scripts/build_docs.py from mlinter/rules.toml. Do not edit by hand. -->"

# Rule prose is authored for a terminal (`mlinter --rule TRF001`), so it mixes deliberate Markdown
# code spans with characters that are markup to kramdown but plain text to a reader: `<Model>Config`,
# `modeling_*.py`, `__init__`. Code spans are passed through untouched and everything between them is
# escaped, which keeps the intended formatting without letting a glob italicise half a sentence.
_CODE_SPAN = re.compile(r"`[^`]*`")


def _escape_prose(chunk: str, *, in_table: bool) -> str:
    chunk = chunk.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    for char in "*_[]":
        chunk = chunk.replace(char, f"\\{char}")
    if in_table:
        chunk = chunk.replace("|", "\\|")
    return chunk


def md_escape(text: str, *, in_table: bool = False) -> str:
    """Neutralise Markdown metacharacters in rule prose, leaving `code spans` intact."""
    parts: list[str] = []
    position = 0
    for match in _CODE_SPAN.finditer(text):
        parts.append(_escape_prose(text[position : match.start()], in_table=in_table))
        # kramdown splits a table row on `|` before parsing inline spans, so a pipe has to be escaped
        # even inside code.
        parts.append(match.group(0).replace("|", "\\|") if in_table else match.group(0))
        position = match.end()
    parts.append(_escape_prose(text[position:], in_table=in_table))
    return "".join(parts)


def yaml_double_quoted(text: str) -> str:
    """Render `text` as a YAML double-quoted scalar, safe for any punctuation a description carries."""
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def rule_module_name(rule_id: str) -> str:
    return f"{rule_id.lower()}.py"


def scope_label(cutoff_date: str | None) -> str:
    """How wide a rule's blast radius is — every model, or only ones added since a cutoff."""
    if not cutoff_date:
        return "All models"
    return f"Models added on or after {cutoff_date}"


def render_rule_page(rule_id: str, spec: dict[str, object], nav_order: int) -> str:
    explanation = cast(dict[str, str], spec["explanation"])
    description = cast(str, spec["description"])
    default_enabled = cast(bool, spec["default_enabled"])
    cutoff_date = cast("str | None", spec["cutoff_date"])
    allowlist = sorted(cast("set[str]", spec["allowlist_models"]))

    default_cell = "Enabled" if default_enabled else "Disabled"
    module = rule_module_name(rule_id)

    lines = [
        "---",
        "layout: default",
        f"title: {rule_id}",
        "parent: Rules",
        f"nav_order: {nav_order}",
        # The one-line summary feeds the search preview and the sidebar tooltip, so a reader scanning
        # 57 near-identical rule codes can tell them apart without opening each one.
        f"description: {yaml_double_quoted(description)}",
        "---",
        "",
        GENERATED_BANNER,
        "",
        f"# {rule_id}",
        "{: .no_toc }",
        "",
        md_escape(description),
        "{: .fs-5 .fw-300 }",
        "",
        "| | |",
        "|---|---|",
        f"| **Default** | {default_cell} |",
        f"| **Scope** | {scope_label(cutoff_date)} |",
        f"| **Source** | [`mlinter/{module}`]({REPO_URL}/blob/main/mlinter/{module}) |",
        f"| **Show in terminal** | `mlinter --rule {rule_id}` |",
        "{: .rule-meta }",
        "",
        "## What it does",
        "",
        md_escape(explanation["what_it_does"]),
        "",
        "## Why is this bad?",
        "",
        md_escape(explanation["why_bad"]),
        "",
        "## Example",
        "",
        "```diff",
        explanation["diff"].strip("\n"),
        "```",
        "",
    ]

    if not default_enabled:
        lines += [
            "## Enabling this rule",
            "",
            f"{rule_id} is off by default. Turn it on for a run with:",
            "",
            "```bash",
            f"mlinter --enable-rules {rule_id}",
            "```",
            "",
        ]

    lines += [
        "## Suppressing this rule",
        "",
        f"Add a `# trf-ignore: {rule_id}` comment on the flagged line or the line directly above it. "
        "See [Suppressing rules](../suppressing.md) for whole-file directives and when a suppression "
        "is the wrong answer.",
        "",
    ]

    if allowlist:
        noun = "model" if len(allowlist) == 1 else "models"
        lines += [
            "## Allowlisted models",
            "",
            f"{len(allowlist)} {noun} are exempt from {rule_id} in `mlinter/rules.toml`, because they "
            "predate the convention and cannot be changed without breaking backward compatibility.",
            "",
            '<details markdown="block">',
            f"<summary>Show the {len(allowlist)} allowlisted {noun}</summary>",
            "",
            "\n".join(f"- `{model}`" for model in allowlist),
            "",
            "</details>",
            "",
        ]

    return "\n".join(lines)


def render_deprecated_rule_page(rule_id: str, spec: dict[str, object], nav_order: int) -> str:
    """The page a retired rule keeps: why it went, and what it means for a project that still names it.

    Deliberately not the live layout — there is no source module to link, no scope, and no example to
    show, and offering `mlinter --rule TRFNNN` would be advertising a command that now exits 2.
    """
    description = cast(str, spec["description"])

    return "\n".join(
        [
            "---",
            "layout: default",
            f"title: {rule_id}",
            "parent: Rules",
            f"nav_order: {nav_order}",
            f"description: {yaml_double_quoted(description)}",
            "---",
            "",
            GENERATED_BANNER,
            "",
            f"# {rule_id}",
            "{: .no_toc }",
            "",
            md_escape(description),
            "{: .fs-5 .fw-300 }",
            "",
            "{: .warning }",
            f"> {rule_id} has been removed from mlinter and never runs. It is absent from "
            f"`mlinter --list-rules`, and asking for it (`mlinter --enable-rules {rule_id}`, "
            f"`mlinter --rule {rule_id}`) exits with an error. The number is retired and is never reused.",
            "",
            "| | |",
            "|---|---|",
            "| **Status** | Removed |",
            "| **Source** | Module deleted — see the [changelog](../changelog.md) |",
            "{: .rule-meta }",
            "",
            "## What this means for your project",
            "",
            f"Nothing to clean up on the linted side: a leftover `# trf-ignore: {rule_id}` comment is "
            "harmless, because mlinter no longer recognises the id at all.",
            "",
            f"A project that ships its own rules TOML must mark `[rules.{rule_id}]` with "
            "`deprecated = true` or drop the table entirely. Leaving it described as an active rule "
            "fails the run with exit code 2, rather than silently linting nothing under that id.",
            "",
        ]
    )


def render_index_page(specs: dict[str, dict[str, object]], deprecated_specs: dict[str, dict[str, object]]) -> str:
    total = len(specs)
    enabled = sum(1 for spec in specs.values() if spec["default_enabled"])

    lines = [
        "---",
        "layout: default",
        "title: Rules",
        "nav_order: 3",
        "has_children: true",
        "has_toc: false",
        "---",
        "",
        GENERATED_BANNER,
        "",
        "# Rules",
        "{: .no_toc }",
        "",
        f"mlinter ships **{total} rules**, **{enabled} of them enabled by default**. Every rule is "
        "static: it reads the file's syntax tree and never imports or runs the model code.",
        "{: .fs-5 .fw-300 }",
        "",
        "Rules whose scope names a date only apply to models contributed to Transformers on or after "
        "it — existing models are grandfathered so a new convention does not retroactively fail the "
        "whole library. Individual models can also be exempted; each rule page lists its own "
        "exemptions.",
        "",
        '<input type="search" id="rule-filter" class="rule-filter" placeholder="Filter '
        f'{total} rules by code or description…" aria-label="Filter rules" autocomplete="off">',
        '<p class="rule-filter-count" id="rule-filter-count" aria-live="polite"></p>',
        "",
        "| Code | What it checks | Default | Scope |",
        "|:-----|:---------------|:--------|:------|",
    ]

    for rule_id in sorted(specs):
        spec = specs[rule_id]
        default_cell = "Enabled" if spec["default_enabled"] else "Disabled"
        cutoff_date = cast("str | None", spec["cutoff_date"])
        scope_cell = cutoff_date if cutoff_date else "All models"
        lines.append(
            f"| [{rule_id}]({rule_id.lower()}.md) "
            f"| {md_escape(cast(str, spec['description']), in_table=True)} "
            f"| {default_cell} "
            f"| {scope_cell} |"
        )

    lines += [
        "{: .rule-table #rule-table }",
        "",
    ]

    # Retired rules get their own table rather than a row in the main one: they are not part of the
    # "N rules" the filter box counts, but a reader who arrived from an old CI log still needs to find
    # out what happened to the number.
    if deprecated_specs:
        one = len(deprecated_specs) == 1
        subject = "rule has" if one else "rules have"
        lines += [
            "## Removed rules",
            "",
            f"{len(deprecated_specs)} {subject} been retired. "
            f"{'It no longer runs' if one else 'They no longer run'}, "
            f"{'it is' if one else 'they are'} not included in the count above, and "
            f"{'its number is' if one else 'their numbers are'} never reused. A leftover "
            "`# trf-ignore` comment naming one is harmless.",
            "",
            "| Code | Why it was removed |",
            "|:-----|:-------------------|",
        ]
        for rule_id in sorted(deprecated_specs):
            description = cast(str, deprecated_specs[rule_id]["description"])
            lines.append(f"| [{rule_id}]({rule_id.lower()}.md) | {md_escape(description, in_table=True)} |")
        lines += [
            "{: .rule-table }",
            "",
        ]

    return "\n".join(lines)


def released_version() -> str:
    """The version from pyproject.toml, which the release process treats as the single source of truth.

    Deliberately not ``mlinter.__version__``: in a checkout that resolves to something like
    ``0.1.2+g24cc4bd``, and a commit hash is noise on a published page.
    """
    data = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    version = data["project"]["version"]
    if not isinstance(version, str) or not version.strip():
        raise SystemExit("pyproject.toml [project].version is missing or not a string")
    return version


def render_changelog_page() -> str:
    """The root CHANGELOG.md with front matter prepended.

    Copied rather than symlinked because Jekyll refuses to follow symlinks out of its source directory,
    and duplicated rather than moved because the changelog has to stay readable on github.com and in a
    source tarball. Its own `# Changelog` heading is left in place as the page title.
    """
    body = CHANGELOG_SRC.read_text(encoding="utf-8")
    front_matter = "\n".join(
        [
            "---",
            "layout: default",
            "title: Changelog",
            "nav_order: 6",
            'description: "Release history for transformers-mlinter, including every rule added in each version."',
            "---",
            "",
            "<!-- Generated by scripts/build_docs.py from CHANGELOG.md. Do not edit by hand. -->",
            "",
        ]
    )
    return f"{front_matter}{body}"


def build(output_dir: Path) -> tuple[int, int]:
    specs = mlinter.TRF_RULE_SPECS
    deprecated_specs = mlinter.DEPRECATED_TRF_RULE_SPECS
    if not specs:
        raise SystemExit("No rules found in mlinter.TRF_RULE_SPECS — refusing to write an empty reference.")

    # Wipe first: a deleted or renumbered rule must not leave an orphan page behind, and only this
    # script's own generated pages live here.
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)

    (output_dir / "index.md").write_text(render_index_page(specs, deprecated_specs) + "\n", encoding="utf-8")
    # One nav_order sequence over live and retired rules together, so the sidebar stays in rule-number
    # order and a retired rule sits where a reader expects it rather than in a pile at the end.
    for nav_order, rule_id in enumerate(sorted(specs | deprecated_specs), start=1):
        if rule_id in deprecated_specs:
            page = render_deprecated_rule_page(rule_id, deprecated_specs[rule_id], nav_order)
        else:
            page = render_rule_page(rule_id, specs[rule_id], nav_order)
        (output_dir / f"{rule_id.lower()}.md").write_text(page + "\n", encoding="utf-8")

    (DOCS_DIR / "changelog.md").write_text(render_changelog_page(), encoding="utf-8")

    # Exposed as site data so a hand-written page can print the version without carrying it in front
    # matter, which would go stale the moment pyproject.toml is bumped.
    version = released_version()
    data_dir = DOCS_DIR / "_data"
    data_dir.mkdir(exist_ok=True)
    (data_dir / "mlinter.yml").write_text(
        "# Generated by scripts/build_docs.py from pyproject.toml. Do not edit by hand.\n"
        f"version: {yaml_double_quoted(version)}\n",
        encoding="utf-8",
    )

    return len(specs), len(deprecated_specs)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory to write the generated rule pages into (default: docs/rules).",
    )
    args = parser.parse_args()

    count, deprecated_count = build(args.output_dir)
    retired = f" ({deprecated_count} retired)" if deprecated_count else ""
    print(f"Wrote {count + deprecated_count} rule pages{retired} + index to {args.output_dir.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
